version: '3.7'

services:
  spark:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8085:8080'
      - '7077:7077'
    volumes:
      - /home/dbt_lab/test_pyspark/pyspark_docker_bitnami/pyscr:/opt/bitnami/spark/pyscr
      - /home/dbt_lab/test_pyspark/pyspark_docker_bitnami/.env:/opt/bitnami/spark/.env

  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G      #<--- adjust accordingly
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  pg_database:
    image: postgres:12.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5439:5432'
    volumes:
      - /home/dbt_lab/test_pyspark/pyspark_docker_bitnami/postgres_vol:/var/lib/postgresql/data
